### ISSUE TITLE
Update roll range table

### ISSUE THREAD

**Issue by taldcroft** [sot/Ska.Sun#18]
The roll range table here (which gets used in sparkles) is not up to date. In particular the "throat" near 135 is wrong.

I think that it might make sense here to use the high resolution "definitive" version from mission planning, even if it is a bit slower to interpolate.

**Comment by jeanconn** [comment]
I think the table is in sparkles.

**Comment by jeanconn** [comment]
(PS my recollection is that we talked about moving it here and did some in https://github.com/sot/Ska.Sun/pull/5 and then decided against it)

**Comment by jeanconn** [comment]
Closed by #19
